### PR TITLE
Fix receipt storage not working issue.

### LINKED ISSUE #347: Receipt Storage not working as expected.

### PR DESCRIPTION
**Pull request by sheexiong**

### CODE REVIEW

File: src/main/java/seedu/eylah/expensesplitter/model/receipt/UniqueReceiptList.java [hunk 1]
```diff
@@ -104,7 +104,18 @@ private boolean receiptsAreUnique(List<Receipt> receipts) {
      * @return true if contain at least a receipt, otherwise false.
      */
     public boolean isContainSingleReceipt() {
-        return internalList.size() != 0;
+        return internalList.size() == 1;
```
Comment (WillySeahh) [inline src/main/java/seedu/eylah/expensesplitter/model/receipt/UniqueReceiptList.java:107]: Glad this works now!

**Review by WillySeahh — APPROVED** [review]
LGTM
