### PR TITLE
Fixed Diet Tracker Bugs 2

### LINKED ISSUE #325: [SELFTEST - DIET] Suggestion to have a command to display currently inputted weight and height
Can either use current `weight` or `height` command or create a new command to display

### LINKED ISSUE #327: [SELFTEST - DIET] Integer overflow issue in the add command.
The calories got the integer overflow issue.

### LINKED ISSUE #332: [SELFTEST - DIET] Adding item with same name and same calories returns me "This food already exists in the food book"
Screenshot 2020-04-10 at 14 31 41

### PR DESCRIPTION
**Pull request by Jarrod-Bob**
Fixed the following:

1. Add Food Calorie Integer Overflow.
2. Duplicate Food addition now possible.

### CODE REVIEW

File: src/test/java/seedu/eylah/diettracker/model/FoodBookTest.java [hunk 1]
```diff
@@ -3,23 +3,23 @@
...
 import static seedu.eylah.diettracker.testutil.TypicalFood.PASTA;
 import static seedu.eylah.diettracker.testutil.TypicalFood.getTypicalFoodBook;
 import static seedu.eylah.testutil.Assert.assertThrows;
+//import java.util.Arrays;
 
-import java.util.Arrays;
 import java.util.Collection;
 import java.util.Collections;
-import java.util.List;
+//import java.util.List;
```
Comment (sheexiong) [inline src/test/java/seedu/eylah/diettracker/model/FoodBookTest.java:14]: maybe can just remove the unused import instead of comment it out.

**Review by sheexiong — APPROVED** [review]
LGTM
